export const NOGATU_PRODUCT_CATALOG = [
  {
    id: 'berry-nad-plus',
    name: 'Berry NAD+',
    sku: 'NKT-BND-001',
    category: 'Supplements',
    image: '/assets/Berry-Nad.png',
    price: 7998,
    rating: 4.9,
    badge: 'New Product',
    shortDescription: 'Berry NAD+ wellness supplement for vitality, recovery, and premium cellular support.',
    featuredScale: 1.18,
    thumbScale: 1.08,
  },
  {
    id: 'nogatu-barley-juice',
    name: 'Nogatu Barley Juice',
    sku: 'NKT-BAR-001',
    category: 'Wellness',
    image: '/assets/Barley-Mix.png',
    price: 850,
    rating: 4.8,
    badge: 'Wellness Pick',
    shortDescription: 'Pure energy and naturally refreshing barley wellness drink.',
    featuredScale: 1.14,
    thumbScale: 1.06,
  },
  {
    id: 'nogatu-glow',
    name: 'Nogatu Glow',
    sku: 'NKT-GLW-001',
    category: 'Supplements',
    image: '/assets/Glow-Pill.png',
    price: 550,
    rating: 4.7,
    badge: 'Glow Care',
    shortDescription: 'L-reduced glutathione support designed for everyday radiance.',
    featuredScale: 1.32,
    thumbScale: 1.14,
  },
  {
    id: 'vitamin-c-collagen',
    name: 'Vitamin C with Collagen & Glutathione',
    sku: 'NKT-VCC-001',
    category: 'Supplements',
    image: '/assets/Vitamin-C-Collagen.png',
    price: 500,
    rating: 4.8,
    badge: 'Daily Support',
    shortDescription: 'Radiance and antioxidant support formula for skin and wellness.',
    featuredScale: 1.22,
    thumbScale: 1.08,
  },
  {
    id: 'chocolate-drink-mix',
    name: 'Chocolate Drink Mix',
    sku: 'NKT-CHO-001',
    category: 'Chocolate',
    image: '/assets/Chox-Mix.png',
    price: 710,
    rating: 4.8,
    badge: 'Rich Blend',
    shortDescription: 'Healthy chocolate drink with herbal and vegetable mix notes.',
    featuredScale: 1.18,
    thumbScale: 1.08,
  },
  {
    id: 'nogatu-coffee-mix',
    name: 'Nogatu Coffee Mix',
    sku: 'NKT-COF-001',
    category: 'Coffee',
    image: '/assets/Coffee-Mix.png',
    price: 495,
    rating: 4.9,
    badge: 'Featured',
    shortDescription: 'Herbal coffee mix crafted for immunity, focus, and daily energy.',
    featuredScale: 1.12,
    thumbScale: 1.04,
  },
  {
    id: 'mangosteen-coffee-mix',
    name: 'Mangosteen Coffee Mix',
    sku: 'NKT-MAN-001',
    category: 'Coffee',
    image: '/assets/Mangoosteen_1.png',
    price: 375,
    rating: 4.9,
    badge: 'Best Seller',
    shortDescription: 'Coffee drink mix with mangosteen and functional botanicals.',
    featuredScale: 1.18,
    thumbScale: 1.08,
  },
  {
    id: 'vitamin-c-zinc-mangosteen',
    name: 'Vitamin C with Zinc & Mangosteen',
    sku: 'NKT-VCZ-001',
    category: 'Supplements',
    image: '/assets/Vitamin-C.png',
    price: 580,
    rating: 4.7,
    badge: 'Immune Boost',
    shortDescription: 'Vitamin support blend with zinc and mangosteen extract.',
    featuredScale: 1.18,
    thumbScale: 1.08,
  },
  {
    id: 'nogatu-black-coffee',
    name: 'Nogatu Black Coffee',
    sku: 'NKT-BLC-001',
    category: 'Coffee',
    image: '/assets/blck-coffee.png',
    price: 250,
    rating: 4.6,
    badge: 'Bold Roast',
    shortDescription: 'Premium black coffee drink mix with a clean, roasted finish.',
    featuredScale: 1.14,
    thumbScale: 1.05,
  },
  {
    id: 'nogatu-max-fuel',
    name: 'Nogatu Max Fuel Coffee Drink Mix',
    sku: 'NKT-MXF-001',
    category: 'Coffee',
    image: '/assets/max-fuel-coffee.png',
    price: 2500,
    rating: 4.9,
    badge: 'Power Blend',
    shortDescription: 'Max fuel coffee blend for endurance, drive, and high-output days.',
    featuredScale: 1.12,
    thumbScale: 1.04,
  },
];

export const NOGATU_PRODUCT_IMAGE_MAP = [
  { match: ['barley juice', 'barley', 'nkt-bar'], image: '/assets/Barley-Mix.png' },
  { match: ['nogatu glow', 'glow', 'nkt-glw'], image: '/assets/Glow-Pill.png' },
  { match: ['collagen', 'glutathione', 'nkt-vcc'], image: '/assets/Vitamin-C-Collagen.png' },
  { match: ['chocolate drink mix', 'chocolate', 'chox', 'nkt-cho'], image: '/assets/Chox-Mix.png' },
  { match: ['nogatu coffee mix', 'coffee mix', 'nkt-cof'], image: '/assets/Coffee-Mix.png' },
  { match: ['mangosteen coffee', 'mangosteen', 'nkt-man'], image: '/assets/Mangoosteen_1.png' },
  { match: ['zinc', 'vitamin c', 'nkt-vcz'], image: '/assets/Vitamin-C.png' },
  { match: ['black coffee', 'blck', 'nkt-blc'], image: '/assets/blck-coffee.png' },
  { match: ['max fuel', 'fuel coffee', 'nkt-mxf'], image: '/assets/max-fuel-coffee.png' },
  { match: ['berry nad', 'nad+', 'berry-nad', 'nkt-bnd'], image: '/assets/Berry-Nad.png' },
];
