import { ROLE_SLUGS } from '@/utils/constants';

export const PERMISSIONS = {
  DASHBOARD_VIEW: 'dashboard:view',
  REPORTS_VIEW: 'reports:view',
  CART_USE: 'cart:use',
  USERS_VIEW: 'users:view',
  USERS_MANAGE: 'users:manage',
  ORDERS_VIEW: 'orders:view',
  ORDERS_CREATE: 'orders:create',
  INVENTORY_VIEW: 'inventory:view',
  GRN_CREATE: 'grn:create',
  DELIVERY_TOKENS_CREATE: 'delivery_tokens:create',
  TRACKING_VIEW: 'tracking:view',
  STOCK_TRANSFERS_CREATE: 'stock_transfers:create',
  PURCHASE_ORDERS_CREATE: 'purchase_orders:create',
  CYCLE_COUNTS_VIEW: 'cycle_counts:view',
  CYCLE_COUNTS_CREATE: 'cycle_counts:create',
  SETTLEMENTS_VIEW: 'settlements:view',
  EXPORTS_GENERATE: 'exports:generate',
  MOBILE_STOCKISTS_MANAGE: 'mobile_stockists:manage',
};

const ROLE_PERMISSIONS = {
  [ROLE_SLUGS.SUPER_ADMIN]: Object.values(PERMISSIONS),
  [ROLE_SLUGS.PROVINCIAL_STOCKIST]: [
    PERMISSIONS.DASHBOARD_VIEW,
    PERMISSIONS.REPORTS_VIEW,
    PERMISSIONS.CART_USE,
    PERMISSIONS.USERS_VIEW,
    PERMISSIONS.USERS_MANAGE,
    PERMISSIONS.ORDERS_VIEW,
    PERMISSIONS.ORDERS_CREATE,
    PERMISSIONS.INVENTORY_VIEW,
    PERMISSIONS.GRN_CREATE,
    PERMISSIONS.DELIVERY_TOKENS_CREATE,
    PERMISSIONS.TRACKING_VIEW,
    PERMISSIONS.STOCK_TRANSFERS_CREATE,
    PERMISSIONS.PURCHASE_ORDERS_CREATE,
    PERMISSIONS.CYCLE_COUNTS_VIEW,
    PERMISSIONS.CYCLE_COUNTS_CREATE,
    PERMISSIONS.SETTLEMENTS_VIEW,
    PERMISSIONS.EXPORTS_GENERATE,
    PERMISSIONS.MOBILE_STOCKISTS_MANAGE,
  ],
  [ROLE_SLUGS.CITY_STOCKIST]: [
    PERMISSIONS.DASHBOARD_VIEW,
    PERMISSIONS.REPORTS_VIEW,
    PERMISSIONS.CART_USE,
    PERMISSIONS.USERS_VIEW,
    PERMISSIONS.USERS_MANAGE,
    PERMISSIONS.ORDERS_VIEW,
    PERMISSIONS.ORDERS_CREATE,
    PERMISSIONS.INVENTORY_VIEW,
    PERMISSIONS.GRN_CREATE,
    PERMISSIONS.DELIVERY_TOKENS_CREATE,
    PERMISSIONS.TRACKING_VIEW,
    PERMISSIONS.STOCK_TRANSFERS_CREATE,
    PERMISSIONS.PURCHASE_ORDERS_CREATE,
    PERMISSIONS.CYCLE_COUNTS_VIEW,
    PERMISSIONS.CYCLE_COUNTS_CREATE,
    PERMISSIONS.SETTLEMENTS_VIEW,
    PERMISSIONS.EXPORTS_GENERATE,
    PERMISSIONS.MOBILE_STOCKISTS_MANAGE,
  ],
  [ROLE_SLUGS.STAFF]: [
    PERMISSIONS.DASHBOARD_VIEW,
    PERMISSIONS.REPORTS_VIEW,
    PERMISSIONS.ORDERS_VIEW,
    PERMISSIONS.INVENTORY_VIEW,
    PERMISSIONS.GRN_CREATE,
    PERMISSIONS.DELIVERY_TOKENS_CREATE,
    PERMISSIONS.TRACKING_VIEW,
    PERMISSIONS.CYCLE_COUNTS_VIEW,
    PERMISSIONS.CYCLE_COUNTS_CREATE,
  ],
  [ROLE_SLUGS.MOBILE_STOCKIST]: [
    PERMISSIONS.CART_USE,
    PERMISSIONS.ORDERS_VIEW,
    PERMISSIONS.ORDERS_CREATE,
    PERMISSIONS.TRACKING_VIEW,
  ],
};

export function normalizeRoleSlug(roleSlug) {
  return roleSlug === ROLE_SLUGS.ADMIN ? ROLE_SLUGS.PROVINCIAL_STOCKIST : roleSlug;
}

export function can(roleSlug, permission) {
  const role = normalizeRoleSlug(roleSlug);
  return Boolean(ROLE_PERMISSIONS[role]?.includes(permission));
}
